// Realistisk exempeldata för Ditec Sisjön (bilvård: rekonditionering,
// lackskydd, rostskydd m.m.). Datumen genereras relativt "idag" så att demot
// alltid ser aktuellt ut och uppföljningslogiken har något att reagera på.
// Flera mejl innehåller registreringsnummer så fordonsuppslaget kan testas.

import type { Lead } from "./types";

function daysAgo(days: number, hour = 9, minute = 0): string {
  const d = new Date();
  d.setDate(d.getDate() - days);
  d.setHours(hour, minute, 0, 0);
  return d.toISOString();
}

function hoursAgo(hours: number): string {
  const d = new Date();
  d.setHours(d.getHours() - hours, 0, 0, 0);
  return d.toISOString();
}

/** Genereras på klienten vid mount för att undvika hydration-krockar. */
export function generateLeads(): Lead[] {
  return [
    {
      id: "1",
      from: "Anna Bergström",
      email: "anna.bergstrom@gmail.com",
      phone: "070-123 45 67",
      subject: "Offert rekond inför bilförsäljning",
      preview:
        "Hej! Jag ska sälja min bil och vill ha en helrekond först. Regnr JHK427...",
      body: "Hej!\n\nJag ska sälja min bil och vill ha en ordentlig helrekond först, både in- och utvändigt. Bilen är en Volvo XC60, regnr JHK 427. Vad kostar det och hur lång tid tar det?\n\nMvh Anna",
      receivedAt: hoursAgo(2),
      channel: "email",
      category: "offert",
      status: "ny",
      priority: "hog",
      service: "Helrekond",
      regnr: "JHK427",
      followUpsSent: 0,
      aiSummary: "Offertförfrågan helrekond inför försäljning, Volvo XC60.",
      aiConfidence: 0.93,
    },
    {
      id: "2",
      from: "Johan Lind",
      email: "johan@lindbygg.se",
      phone: "0708-88 77 66",
      subject: "Lackskydd på ny firmabil – offert",
      preview:
        "Vi har köpt en ny servicebil och vill ha keramiskt lackskydd direkt...",
      body: "Hej,\n\nVi på Lind Bygg har köpt en ny servicebil (VW Transporter, reg MRT881) och vill skydda lacken direkt med keramiskt lackskydd. Kan ni ta den nästa vecka? Skicka gärna offert.\n\n/ Johan",
      receivedAt: hoursAgo(6),
      channel: "email",
      category: "offert",
      status: "obesvarad",
      priority: "hog",
      service: "Lackskydd",
      regnr: "MRT881",
      followUpsSent: 0,
      aiSummary: "Offert keramiskt lackskydd på ny firmabil, önskar tid nästa vecka.",
      aiConfidence: 0.9,
    },
    {
      id: "3",
      from: "Sara Nyström",
      email: "sara.nystrom@hotmail.com",
      subject: "Vill boka invändig rengöring",
      preview: "Hej! Jag vill boka in en invändig rengöring, det har blivit fläckar...",
      body: "Hej!\n\nJag vill boka in en invändig rengöring av min bil (Volvo V60, KLP092). Det har blivit en del fläckar i sätena efter barnen. Har ni någon tid i september?\n\nTack, Sara",
      receivedAt: hoursAgo(20),
      channel: "webbformular",
      category: "bokning",
      status: "ny",
      priority: "medel",
      service: "Invändig rengöring",
      regnr: "KLP092",
      followUpsSent: 0,
      aiSummary: "Vill boka invändig rengöring pga fläckar i sätena.",
      aiConfidence: 0.95,
    },
    {
      id: "4",
      from: "Peter Alm",
      email: "peter.alm@foretaget.se",
      phone: "031-22 33 44",
      subject: "Fråga: keramiskt lackskydd eller vax?",
      preview: "Undrar vad ni rekommenderar – keramiskt lackskydd eller vanlig vaxning...",
      body: "Hej,\n\nJag undrar vad ni rekommenderar för min BMW 320d (TRS334) – keramiskt lackskydd eller vanlig vaxning? Vill ha rådgivning om vad som håller bäst innan jag bestämmer mig.\n\nMvh Peter",
      receivedAt: daysAgo(1, 14),
      channel: "email",
      category: "konsultation",
      status: "obesvarad",
      priority: "medel",
      service: "Lackskydd",
      regnr: "TRS334",
      followUpsSent: 0,
      aiSummary: "Rådgivning om keramiskt lackskydd kontra vax.",
      aiConfidence: 0.82,
    },
    {
      id: "5",
      from: "Familjen Karlsson",
      email: "karlsson.hem@gmail.com",
      subject: "Offert helrekond familjebil",
      preview: "Vår XC90 behöver en rejäl genomgång inför semestern...",
      body: "Hej!\n\nVår familjebil (Volvo XC90, OWL763) behöver en rejäl genomgång inför semestern – tvätt, vax och invändig rengöring. Vad kostar en helrekond och har ni tid vecka 35?\n\nHälsningar Karlssons",
      receivedAt: daysAgo(2, 11),
      channel: "email",
      category: "offert",
      status: "besvarad",
      priority: "medel",
      service: "Helrekond",
      regnr: "OWL763",
      lastContactAt: daysAgo(1, 16),
      followUpsSent: 0,
      aiSummary: "Helrekond familjebil inför semestern, önskar vecka 35.",
      aiConfidence: 0.88,
    },
    // --- Offerter skickade, väntar på svar (driver uppföljningar) ---
    {
      id: "6",
      from: "Mikael Öberg",
      email: "mikael.oberg@gmail.com",
      phone: "073-555 12 34",
      subject: "Offert rostskyddsbehandling",
      preview: "Tack för svar, återkommer om offerten på rostskyddet...",
      body: "Hej,\n\nTack för snabbt svar. Jag återkommer om offerten för rostskyddsbehandling på min Audi A4 (DFG215).\n\nMvh Mikael",
      receivedAt: daysAgo(4, 10),
      channel: "email",
      category: "offert",
      status: "offert_skickad",
      priority: "medel",
      service: "Rostskydd",
      regnr: "DFG215",
      quoteSentAt: daysAgo(4, 15),
      quoteAmount: 4900,
      lastContactAt: daysAgo(4, 15),
      followUpsSent: 0,
      aiSummary: "Offert rostskyddsbehandling skickad, kund ej återkommit.",
      aiConfidence: 0.9,
    },
    {
      id: "7",
      from: "Lena Fransson",
      email: "lena.fransson@telia.com",
      subject: "Offert rekond SUV",
      preview: "Hej, kan jag få en offert på rekond av vår Toyota RAV4...",
      body: "Hej,\n\nKan jag få en offert på en komplett rekond av vår Toyota RAV4 (PNB540)? Både utvändig polering och invändigt.\n\nMvh Lena",
      receivedAt: daysAgo(9, 9),
      channel: "webbformular",
      category: "offert",
      status: "offert_skickad",
      priority: "hog",
      service: "Helrekond",
      regnr: "PNB540",
      quoteSentAt: daysAgo(8, 13),
      quoteAmount: 3900,
      lastContactAt: daysAgo(8, 13),
      followUpsSent: 1,
      aiSummary: "Offert helrekond SUV, en påminnelse redan skickad.",
      aiConfidence: 0.92,
    },
    {
      id: "8",
      from: "Sisjö Åkeri AB",
      email: "info@sisjoakeri.se",
      phone: "031-77 88 99",
      subject: "Offert löpande rekond av skåpbilar",
      preview: "Vi behöver återkommande rekond av våra skåpbilar och undrar om pris...",
      body: "Hej,\n\nVi behöver återkommande rekond och invändig sanering av vår fordonsflotta (ca 6 skåpbilar, t.ex. Mercedes Sprinter RKM118). Vi fick er offert men behöver stämma av internt. Återkommer.\n\nMvh Sisjö Åkeri",
      receivedAt: daysAgo(16, 10),
      channel: "email",
      category: "offert",
      status: "offert_skickad",
      priority: "hog",
      service: "Helrekond",
      regnr: "RKM118",
      quoteSentAt: daysAgo(15, 11),
      quoteAmount: 18500,
      lastContactAt: daysAgo(15, 11),
      followUpsSent: 1,
      aiSummary: "Större återkommande flottavtal, offert väntar på beslut.",
      aiConfidence: 0.87,
    },
    {
      id: "9",
      from: "Erik Sandberg",
      email: "erik.sandberg@outlook.com",
      subject: "Offert rekond",
      preview: "Tack för offerten, ska titta på den...",
      body: "Hej,\n\nTack för offerten på rekond av min Kia (BHT609). Ska titta närmare på den och återkommer.\n\nMvh Erik",
      receivedAt: daysAgo(36, 9),
      channel: "email",
      category: "offert",
      status: "offert_skickad",
      priority: "lag",
      service: "Rekonditionering",
      regnr: "BHT609",
      quoteSentAt: daysAgo(35, 14),
      quoteAmount: 1950,
      lastContactAt: daysAgo(12, 10),
      followUpsSent: 4,
      aiSummary: "Offert rekond, fyra uppföljningar skickade utan svar.",
      aiConfidence: 0.9,
    },
    // --- Bokade ---
    {
      id: "10",
      from: "Camilla Ek",
      email: "camilla.ek@gmail.com",
      phone: "070-999 88 77",
      subject: "Tack – vi kör på rekonden!",
      preview: "Perfekt, vi tackar ja till offerten och bokar in den 22:a...",
      body: "Hej!\n\nPerfekt, vi tackar ja till offerten och bokar in rekond av vår V90 (SVL472) den 22:a. Hör av er om ni behöver något mer.\n\nTack Camilla",
      receivedAt: daysAgo(5, 13),
      channel: "email",
      category: "bokning",
      status: "bokad",
      priority: "medel",
      service: "Helrekond",
      regnr: "SVL472",
      quoteSentAt: daysAgo(9, 10),
      quoteAmount: 3200,
      lastContactAt: daysAgo(5, 15),
      followUpsSent: 1,
      aiSummary: "Kund har tackat ja och bokat rekond den 22:a.",
      aiConfidence: 0.97,
    },
    {
      id: "11",
      from: "Bilfirma Väst AB",
      email: "verkstad@bilfirmavast.se",
      subject: "Bokning lackskydd på lagerbilar",
      preview: "Vi vill boka in lackskydd på våra nya lagerbilar löpande...",
      body: "Hej,\n\nVi vill boka in keramiskt lackskydd på våra nya lagerbilar löpande, ca 4 bilar i månaden. När kan ni börja?\n\nMvh Bilfirma Väst",
      receivedAt: daysAgo(3, 10),
      channel: "email",
      category: "bokning",
      status: "bokad",
      priority: "medel",
      service: "Lackskydd",
      lastContactAt: daysAgo(2, 11),
      followUpsSent: 0,
      aiSummary: "Bilfirma bokar löpande lackskydd på lagerbilar.",
      aiConfidence: 0.96,
    },
    // --- Ingen affär ---
    {
      id: "12",
      from: "Tomas Holm",
      email: "tomas.holm@gmail.com",
      subject: "Re: Offert rostskydd",
      preview: "Tack men vi valde en annan verkstad den här gången...",
      body: "Hej,\n\nTack för offerten men vi valde en annan verkstad för rostskyddet på vår Qashqai (GRD338) den här gången. Kanske en annan gång!\n\nMvh Tomas",
      receivedAt: daysAgo(7, 15),
      channel: "email",
      category: "offert",
      status: "ingen_affar",
      priority: "lag",
      service: "Rostskydd",
      regnr: "GRD338",
      quoteSentAt: daysAgo(14, 10),
      quoteAmount: 4200,
      lastContactAt: daysAgo(7, 15),
      followUpsSent: 2,
      aiSummary: "Kund tackade nej, valde annan verkstad.",
      aiConfidence: 0.94,
    },
    // --- Övrigt ---
    {
      id: "13",
      from: "Fakturor Nordström AB",
      email: "faktura@nordstrom.se",
      subject: "Påminnelse faktura 4471",
      preview: "Detta är en påminnelse gällande obetald faktura...",
      body: "Hej,\n\nDetta är en påminnelse gällande faktura 4471 för levererade förbrukningsartiklar. Vänligen betala snarast.\n\nMvh Ekonomi",
      receivedAt: daysAgo(1, 8),
      channel: "email",
      category: "ovrigt",
      status: "obesvarad",
      priority: "lag",
      followUpsSent: 0,
      aiSummary: "Leverantörsfaktura/påminnelse – ej en kundförfrågan.",
      aiConfidence: 0.85,
    },
    {
      id: "14",
      from: "Sofia Ahmed",
      email: "sofia.ahmed@gmail.com",
      subject: "Vilken behandling passar min bil?",
      preview: "Hej! Vi är osäkra på om vi behöver rekond eller bara en tvätt...",
      body: "Hej!\n\nVi är osäkra på om vår bil (Volvo V40, MJP701) behöver en komplett rekond eller bara en ordentlig tvätt och vax. Kan ni hjälpa oss välja rätt? Bilen är 7 år och har lite repor i lacken.\n\nMvh Sofia",
      receivedAt: daysAgo(2, 17),
      channel: "webbformular",
      category: "konsultation",
      status: "ny",
      priority: "medel",
      service: "Rekonditionering",
      regnr: "MJP701",
      followUpsSent: 0,
      aiSummary: "Vill ha hjälp att välja mellan rekond och tvätt/vax.",
      aiConfidence: 0.8,
    },
  ];
}
