// Realistisk exempeldata för Ditec Sisjön (städ- och lokalvårdstjänster).
// Datumen genereras relativt "idag" så att demot alltid ser aktuellt ut och
// uppföljningslogiken har något att reagera på.

import type { Lead } from "./types";

function daysAgo(days: number, hour = 9, minute = 0): string {
  const d = new Date();
  d.setDate(d.getDate() - days);
  d.setHours(hour, minute, 0, 0);
  return d.toISOString();
}

function hoursAgo(hours: number): string {
  const d = new Date();
  d.setHours(d.getHours() - hours, 0, 0, 0);
  return d.toISOString();
}

/** Genereras på klienten vid mount för att undvika hydration-krockar. */
export function generateLeads(): Lead[] {
  return [
    {
      id: "1",
      from: "Anna Bergström",
      email: "anna.bergstrom@gmail.com",
      phone: "070-123 45 67",
      subject: "Offert flyttstädning 3:a i Askim",
      preview:
        "Hej! Vi flyttar den 30:e och behöver flyttstädning av vår 3:a på 78 kvm...",
      body: "Hej!\n\nVi flyttar den 30:e augusti och behöver flyttstädning av vår lägenhet, en 3:a på 78 kvm i Askim. Vad skulle det kosta och kan ni garantera godkänt vid besiktning?\n\nMvh Anna",
      receivedAt: hoursAgo(2),
      channel: "email",
      category: "offert",
      status: "ny",
      priority: "hog",
      service: "Flyttstädning",
      followUpsSent: 0,
      aiSummary: "Offertförfrågan flyttstädning 78 kvm, flytt om ca 4 veckor.",
      aiConfidence: 0.93,
    },
    {
      id: "2",
      from: "Johan Lind",
      email: "johan@lindbygg.se",
      phone: "0708-88 77 66",
      subject: "Byggstädning efter renovering – kontorslokal",
      preview:
        "Vi har renoverat en kontorslokal på 220 kvm och behöver byggstädning innan...",
      body: "Hej,\n\nVi på Lind Bygg har renoverat en kontorslokal på 220 kvm i Sisjön och behöver byggstädning innan inflyttning nästa vecka. Kan ni komma på tisdag? Skicka gärna en offert.\n\n/ Johan",
      receivedAt: hoursAgo(6),
      channel: "email",
      category: "offert",
      status: "obesvarad",
      priority: "hog",
      service: "Byggstädning",
      followUpsSent: 0,
      aiSummary: "Brådskande byggstädning 220 kvm, önskar tid redan nästa vecka.",
      aiConfidence: 0.9,
    },
    {
      id: "3",
      from: "Sara Nyström",
      email: "sara.nystrom@hotmail.com",
      subject: "Vill boka hemstädning varannan vecka",
      preview: "Hej! Jag vill boka in hemstädning varannan vecka, gärna med start...",
      body: "Hej!\n\nJag vill boka in återkommande hemstädning varannan vecka, gärna med start i september. Villa på 140 kvm i Hovås. Hur går jag vidare?\n\nTack, Sara",
      receivedAt: hoursAgo(20),
      channel: "webbformular",
      category: "bokning",
      status: "ny",
      priority: "medel",
      service: "Hemstädning",
      followUpsSent: 0,
      aiSummary: "Vill boka återkommande hemstädning varannan vecka från september.",
      aiConfidence: 0.95,
    },
    {
      id: "4",
      from: "Peter Alm",
      email: "peter.alm@företaget.se",
      phone: "031-22 33 44",
      subject: "Fråga om ni tar kontorsstädning nattetid",
      preview: "Undrar om det är möjligt att få kontoret städat på kvällar/nätter...",
      body: "Hej,\n\nVi undrar om det går att få vårt kontor (ca 400 kvm) städat på kvällar eller nätter, samt hur ofta ni rekommenderar. Vill gärna ha rådgivning kring upplägg innan vi bestämmer oss.\n\nMvh Peter",
      receivedAt: daysAgo(1, 14),
      channel: "email",
      category: "konsultation",
      status: "obesvarad",
      priority: "medel",
      service: "Kontorsstädning",
      followUpsSent: 0,
      aiSummary: "Rådgivning om upplägg och frekvens för kontorsstädning nattetid.",
      aiConfidence: 0.82,
    },
    {
      id: "5",
      from: "Familjen Karlsson",
      email: "karlsson.hem@gmail.com",
      subject: "Offert storstädning inför fest",
      preview: "Vi ska ha 50-årskalas och vill storstäda hela huset innan...",
      body: "Hej!\n\nVi ska ha 50-årskalas och vill storstäda hela huset (villa 160 kvm) veckan innan. Vad kostar en storstädning och har ni tid vecka 35?\n\nHälsningar Karlssons",
      receivedAt: daysAgo(2, 11),
      channel: "email",
      category: "offert",
      status: "besvarad",
      priority: "medel",
      service: "Storstädning",
      lastContactAt: daysAgo(1, 16),
      followUpsSent: 0,
      aiSummary: "Storstädning villa 160 kvm inför fest vecka 35.",
      aiConfidence: 0.88,
    },
    // --- Offerter skickade, väntar på svar (driver uppföljningar) ---
    {
      id: "6",
      from: "Mikael Öberg",
      email: "mikael.oberg@gmail.com",
      phone: "073-555 12 34",
      subject: "Offert fönsterputs villa",
      preview: "Tack för snabbt svar, återkommer om offerten...",
      body: "Hej,\n\nTack för snabbt svar. Jag återkommer om offerten för fönsterputs på villan.\n\nMvh Mikael",
      receivedAt: daysAgo(4, 10),
      channel: "email",
      category: "offert",
      status: "offert_skickad",
      priority: "medel",
      service: "Fönsterputs",
      quoteSentAt: daysAgo(4, 15),
      quoteAmount: 2400,
      lastContactAt: daysAgo(4, 15),
      followUpsSent: 0,
      aiSummary: "Offert fönsterputs skickad, kund ej återkommit.",
      aiConfidence: 0.9,
    },
    {
      id: "7",
      from: "Lena Fransson",
      email: "lena.fransson@telia.com",
      subject: "Offert flyttstädning radhus",
      preview: "Hej, kan jag få en offert på flyttstädning av vårt radhus...",
      body: "Hej,\n\nKan jag få en offert på flyttstädning av vårt radhus på 110 kvm? Flytt sker i slutet av månaden.\n\nMvh Lena",
      receivedAt: daysAgo(9, 9),
      channel: "webbformular",
      category: "offert",
      status: "offert_skickad",
      priority: "hog",
      service: "Flyttstädning",
      quoteSentAt: daysAgo(8, 13),
      quoteAmount: 3900,
      lastContactAt: daysAgo(8, 13),
      followUpsSent: 1,
      aiSummary: "Offert flyttstädning radhus, en påminnelse redan skickad.",
      aiConfidence: 0.92,
    },
    {
      id: "8",
      from: "Restaurang Vågen AB",
      email: "info@restaurangvagen.se",
      phone: "031-77 88 99",
      subject: "Offert daglig lokalvård restaurang",
      preview: "Vi behöver daglig städning av vår restaurang och undrar om pris...",
      body: "Hej,\n\nVi behöver daglig lokalvård av vår restaurang (matsal + kök, ca 300 kvm). Vi fick er offert men behöver stämma av internt. Återkommer.\n\nMvh Restaurang Vågen",
      receivedAt: daysAgo(16, 10),
      channel: "email",
      category: "offert",
      status: "offert_skickad",
      priority: "hog",
      service: "Kontorsstädning",
      quoteSentAt: daysAgo(15, 11),
      quoteAmount: 18500,
      lastContactAt: daysAgo(15, 11),
      followUpsSent: 1,
      aiSummary: "Större återkommande lokalvårdsavtal, offert väntar på beslut.",
      aiConfidence: 0.87,
    },
    {
      id: "9",
      from: "Erik Sandberg",
      email: "erik.sandberg@outlook.com",
      subject: "Offert hemstädning",
      preview: "Tack för offerten, ska titta på den...",
      body: "Hej,\n\nTack för offerten på hemstädning. Ska titta närmare på den och återkommer.\n\nMvh Erik",
      receivedAt: daysAgo(36, 9),
      channel: "email",
      category: "offert",
      status: "offert_skickad",
      priority: "lag",
      service: "Hemstädning",
      quoteSentAt: daysAgo(35, 14),
      quoteAmount: 1450,
      lastContactAt: daysAgo(12, 10),
      followUpsSent: 4,
      aiSummary: "Offert hemstädning, fyra uppföljningar skickade utan svar.",
      aiConfidence: 0.9,
    },
    // --- Bokade ---
    {
      id: "10",
      from: "Camilla Ek",
      email: "camilla.ek@gmail.com",
      phone: "070-999 88 77",
      subject: "Tack – vi kör på flyttstädningen!",
      preview: "Perfekt, vi tackar ja till offerten och bokar in den 22:a...",
      body: "Hej!\n\nPerfekt, vi tackar ja till offerten och bokar in flyttstädning den 22:a. Hör av er om ni behöver kod till porten.\n\nTack Camilla",
      receivedAt: daysAgo(5, 13),
      channel: "email",
      category: "bokning",
      status: "bokad",
      priority: "medel",
      service: "Flyttstädning",
      quoteSentAt: daysAgo(9, 10),
      quoteAmount: 3200,
      lastContactAt: daysAgo(5, 15),
      followUpsSent: 1,
      aiSummary: "Kund har tackat ja och bokat flyttstädning den 22:a.",
      aiConfidence: 0.97,
    },
    {
      id: "11",
      from: "BRF Eklyckan",
      email: "styrelsen@brfeklyckan.se",
      subject: "Bokning trappstädning trapphus",
      preview: "Vi vill boka veckovis trappstädning för våra tre trapphus...",
      body: "Hej,\n\nStyrelsen har beslutat att boka er för veckovis trappstädning av våra tre trapphus. När kan ni börja?\n\nMvh Styrelsen BRF Eklyckan",
      receivedAt: daysAgo(3, 10),
      channel: "email",
      category: "bokning",
      status: "bokad",
      priority: "medel",
      service: "Trappstädning",
      lastContactAt: daysAgo(2, 11),
      followUpsSent: 0,
      aiSummary: "BRF bokar veckovis trappstädning för tre trapphus.",
      aiConfidence: 0.96,
    },
    // --- Ingen affär ---
    {
      id: "12",
      from: "Tomas Holm",
      email: "tomas.holm@gmail.com",
      subject: "Re: Offert fönsterputs",
      preview: "Tack men vi valde en annan leverantör den här gången...",
      body: "Hej,\n\nTack för offerten men vi valde en annan leverantör den här gången. Kanske en annan gång!\n\nMvh Tomas",
      receivedAt: daysAgo(7, 15),
      channel: "email",
      category: "offert",
      status: "ingen_affar",
      priority: "lag",
      service: "Fönsterputs",
      quoteSentAt: daysAgo(14, 10),
      quoteAmount: 1800,
      lastContactAt: daysAgo(7, 15),
      followUpsSent: 2,
      aiSummary: "Kund tackade nej, valde annan leverantör.",
      aiConfidence: 0.94,
    },
    // --- Övrigt ---
    {
      id: "13",
      from: "Fakturor Nordström AB",
      email: "faktura@nordstrom.se",
      subject: "Påminnelse faktura 4471",
      preview: "Detta är en påminnelse gällande obetald faktura...",
      body: "Hej,\n\nDetta är en påminnelse gällande faktura 4471. Vänligen betala snarast.\n\nMvh Ekonomi",
      receivedAt: daysAgo(1, 8),
      channel: "email",
      category: "ovrigt",
      status: "obesvarad",
      priority: "lag",
      followUpsSent: 0,
      aiSummary: "Leverantörsfaktura/påminnelse – ej en kundförfrågan.",
      aiConfidence: 0.85,
    },
    {
      id: "14",
      from: "Sofia Ahmed",
      email: "sofia.ahmed@gmail.com",
      subject: "Undrar vilken städtjänst som passar oss",
      preview: "Hej! Vi är osäkra på om vi behöver hemstädning eller storstädning...",
      body: "Hej!\n\nVi är osäkra på om vi behöver återkommande hemstädning eller bara en storstädning då och då. Kan ni hjälpa oss välja rätt? Villa 120 kvm, två barn och hund.\n\nMvh Sofia",
      receivedAt: daysAgo(2, 17),
      channel: "webbformular",
      category: "konsultation",
      status: "ny",
      priority: "medel",
      service: "Hemstädning",
      followUpsSent: 0,
      aiSummary: "Vill ha hjälp att välja mellan hemstädning och storstädning.",
      aiConfidence: 0.8,
    },
  ];
}
